# Generated by Django 4.2.7 on 2023-11-24 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Đang chờ', 'Pending'), ('Đang giao hàng', 'Out For Shipping'), ('Hoàn thành', 'Completed'), ('Đã hủy', 'Canceled')], default='Đang chờ', max_length=100),
        ),
    ]
