# Generated by Django 4.2.7 on 2024-03-28 12:10

from django.db import migrations, models
import django.db.models.deletion
import store.models.products


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0010_alter_reviewrating_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Batch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("expiry_date", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("move_date", models.DateTimeField()),
                (
                    "Batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="store.batch"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=150)),
                ("name", models.CharField(max_length=150)),
                ("unit", models.CharField(default="sản phẩm", max_length=30)),
                ("original_price", models.IntegerField(default=0)),
                ("sell_price", models.IntegerField(default=0)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=store.models.products.get_file_path,
                    ),
                ),
                (
                    "status",
                    models.BooleanField(default=False, help_text="0=default, 1=Hidden"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.category",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="batch",
            name="Product2",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="store.product2"
            ),
        ),
    ]
