# Generated by Django 4.2.7 on 2024-04-24 07:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0012_alter_product2_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="product2",
            name="expiry_period",
            field=models.IntegerField(default=0, help_text="Tính bằng 'ngày'"),
        ),
        migrations.AlterField(
            model_name="batch",
            name="expiry_date",
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name="batch",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
