# Generated by Django 4.2.7 on 2024-04-24 09:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0013_product2_expiry_period_alter_batch_expiry_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="batch",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="stock",
            name="Batch",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="store.batch",
            ),
        ),
    ]
