# Generated by Django 4.2.7 on 2024-04-24 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0014_batch_created_at_alter_stock_batch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="move_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
