# Generated by Django 4.2.7 on 2024-04-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0016_alter_batch_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batch",
            name="id",
            field=models.CharField(
                editable=False, max_length=20, primary_key=True, serialize=False
            ),
        ),
    ]
