# Generated by Django 4.2.7 on 2024-04-25 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0017_alter_batch_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="batch",
            name="Product2",
        ),
        migrations.RemoveField(
            model_name="product",
            name="stock",
        ),
        migrations.AddField(
            model_name="batch",
            name="Product",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="store.product",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="batch",
            name="status",
            field=models.BooleanField(default=True, help_text="0=Ẩn, 1=Hiện"),
        ),
        migrations.AddField(
            model_name="product",
            name="expiry_period",
            field=models.IntegerField(default=0, help_text="Tính bằng 'ngày'"),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="store.category"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.BooleanField(default=True, help_text="0=Ẩn, 1=Hiện"),
        ),
        migrations.DeleteModel(
            name="Product2",
        ),
    ]
