# Generated by Django 4.2.7 on 2024-05-27 18:26

from django.db import migrations, models
import store.models.categories
import store.models.products
import store.storage


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0018_remove_batch_product2_remove_product_stock_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=store.storage.StaticStorage,
                upload_to=store.models.categories.get_file_path,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=store.storage.StaticStorage,
                upload_to=store.models.products.get_file_path,
            ),
        ),
    ]
