# Generated by Django 4.2.7 on 2024-05-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0020_orderitem_stock"),
    ]

    operations = [
        migrations.CreateModel(
            name="Test1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock", models.JSONField(default=list)),
            ],
        ),
    ]
