# Generated by Django 4.2.7 on 2024-05-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0021_test1"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="stock",
            field=models.JSONField(default=list),
        ),
    ]
