# Generated by Django 4.2.7 on 2024-06-01 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0023_order_processed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="processed",
            field=models.BooleanField(blank=True),
        ),
    ]
