# Generated by Django 4.2.7 on 2024-06-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0024_alter_order_processed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="note",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
    ]
