# Generated by Django 4.2.7 on 2024-06-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0025_alter_order_note"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stock",
            name="Batch",
        ),
        migrations.DeleteModel(
            name="Test1",
        ),
        migrations.AddField(
            model_name="batch",
            name="quantity",
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name="Stock",
        ),
    ]
