# Generated by Django 4.2.7 on 2024-06-02 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0027_rename_stock_orderitem_batch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="batch",
            field=models.JSONField(default=dict),
        ),
    ]
