# Generated by Django 4.2.7 on 2024-06-24 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("store", "0029_alter_batch_options_alter_category_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cart",
            options={"verbose_name_plural": "Giỏ hàng"},
        ),
        migrations.AlterField(
            model_name="cart",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Tài khoản",
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.localtime, verbose_name="Ngày tạo"
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="store.product",
                verbose_name="Sản phẩm",
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="product_qty",
            field=models.IntegerField(verbose_name="Số lượng"),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(default="", help_text="Bỏ trống", max_length=150),
        ),
    ]
