# Generated by Django 4.2.7 on 2024-09-17 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0031_order_city_name_order_district_name_order_ward_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="sell_price",
            new_name="sell_price",
        ),
    ]
