# Generated by Django 4.2.7 on 2024-09-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0032_rename_sale_price_product_sell_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="unit",
            field=models.IntegerField(verbose_name="Khối lượng (gram)"),
        ),
    ]
