# Generated by Django 4.2.7 on 2024-06-17 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_address_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="account",
            options={"verbose_name_plural": "Tài khoản"},
        ),
        migrations.AlterModelOptions(
            name="address",
            options={"verbose_name_plural": "Địa chỉ"},
        ),
        migrations.AlterField(
            model_name="account",
            name="date_joined",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Ngày tham gia"),
        ),
        migrations.AlterField(
            model_name="account",
            name="gender",
            field=models.CharField(
                choices=[
                    ("Nam", "Male"),
                    ("Nữ", "Female"),
                    ("Không xác định", "Not Specified"),
                ],
                default="Không xác định",
                max_length=15,
                verbose_name="Giới tính",
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="Kích hoạt"),
        ),
        migrations.AlterField(
            model_name="account",
            name="is_admin",
            field=models.BooleanField(default=False, verbose_name="Là admin"),
        ),
        migrations.AlterField(
            model_name="account",
            name="is_staff",
            field=models.BooleanField(default=False, verbose_name="Là staff"),
        ),
        migrations.AlterField(
            model_name="account",
            name="is_superadmin",
            field=models.BooleanField(default=False, verbose_name="Là superadmin"),
        ),
        migrations.AlterField(
            model_name="account",
            name="last_login",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Đăng nhập lần cuối"
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Tên người dùng"),
        ),
        migrations.AlterField(
            model_name="account",
            name="phone",
            field=models.CharField(max_length=10, verbose_name="Số điện thoại"),
        ),
        migrations.AlterField(
            model_name="address",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Tài khoản",
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="city",
            field=models.CharField(
                default="", max_length=100, verbose_name="Mã Thành phố/Tỉnh"
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="district",
            field=models.CharField(
                default="", max_length=100, verbose_name="Mã Quận/Huyện"
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="specific_address",
            field=models.CharField(
                default="", max_length=200, verbose_name="Địa chỉ cụ thể"
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="ward",
            field=models.CharField(
                default="", max_length=100, verbose_name="Mã Phường/Xã"
            ),
        ),
    ]
