# Generated by Django 4.2.7 on 2023-12-07 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('momo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinfo',
            name='order',
            field=models.CharField(max_length=50),
        ),
    ]
