# Generated by Django 4.2.7 on 2023-12-08 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('momo', '0002_alter_paymentinfo_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentinfo',
            name='signature',
        ),
    ]
