# Generated by Django 4.2.7 on 2023-12-08 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('momo', '0003_remove_paymentinfo_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinfo',
            name='resultCode',
            field=models.IntegerField(default=0),
        ),
    ]
