# Generated by Django 4.2.7 on 2024-05-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("momo", "0005_paymentinfo_refund_status_paymentinfo_transid"),
    ]

    operations = [
        migrations.CreateModel(
            name="temp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("paymentinfo", models.JSONField(default=dict)),
            ],
        ),
    ]
