# Generated by Django 4.2.7 on 2024-05-31 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("momo", "0006_temp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="temp",
            name="paymentinfo",
        ),
        migrations.AddField(
            model_name="temp",
            name="amount",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="temp",
            name="extraData",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="temp",
            name="message",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="temp",
            name="orderId",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="temp",
            name="orderInfo",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="temp",
            name="orderType",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="temp",
            name="partnerCode",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="temp",
            name="payType",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="temp",
            name="requestId",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="temp",
            name="responseTime",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="temp",
            name="resultCode",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="temp",
            name="signature",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="temp",
            name="transId",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
