# Generated by Django 4.2.7 on 2024-06-01 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("momo", "0007_remove_temp_paymentinfo_temp_amount_temp_extradata_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="resultcode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField(default=dict)),
            ],
        ),
    ]
