# Generated by Django 4.2.7 on 2024-06-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("momo", "0008_resultcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="temp",
            name="amount",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="temp",
            name="responseTime",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="temp",
            name="resultCode",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="temp",
            name="transId",
            field=models.TextField(blank=True),
        ),
    ]
