# Generated by Django 4.2.7 on 2024-06-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("momo", "0009_alter_temp_amount_alter_temp_responsetime_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="temp",
        ),
        migrations.RemoveField(
            model_name="paymentinfo",
            name="order",
        ),
        migrations.RemoveField(
            model_name="paymentinfo",
            name="refund_status",
        ),
        migrations.AddField(
            model_name="paymentinfo",
            name="amount",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="paymentinfo",
            name="extraData",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="paymentinfo",
            name="message",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="paymentinfo",
            name="orderId",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="paymentinfo",
            name="orderInfo",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="paymentinfo",
            name="orderType",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="paymentinfo",
            name="partnerCode",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="paymentinfo",
            name="payType",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="paymentinfo",
            name="requestId",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="paymentinfo",
            name="responseTime",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="paymentinfo",
            name="signature",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="paymentinfo",
            name="resultCode",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="paymentinfo",
            name="transId",
            field=models.TextField(blank=True),
        ),
    ]
