# Generated by Django 4.2.7 on 2024-06-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("momo", "0010_delete_temp_remove_paymentinfo_order_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentinfo",
            name="orderId",
            field=models.TextField(blank=True, verbose_name="Mã vận đơn"),
        ),
    ]
